import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gql } from "@apollo/client";
import { client } from "../lib/apollo";
import Pick from '../components/pick';

export default function Home({page, picks}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<main className='boxed-container'>
      
<h1>{page.Haupttitel}</h1>

<ul>
{picks.slice(0, 4).map((pick) => {
  return <li key={pick.attributes.Slug}>
    <Pick pick={pick}></Pick>
  </li>;
})}
</ul>


 </main>     
    </div>
  )
}







export async function getStaticProps(){


 const GET_HOMEPAGE = gql`
 query {startseite{data{attributes{Haupttitel}}}}
 `


 const GET_PICKS = gql `
 query {
  picks {
    data {
      attributes {
        Slug
       PickTitel
        Steckbrief
        shortTitle
        Bild{data{attributes{url}}}
        stadtteile{data{attributes{Name}}}
      }
    }
  }
}
 `




 const response = await client.query({
  query: GET_HOMEPAGE
 })


 const picksResponse = await client.query({
  query: GET_PICKS
 }) 
 

  const page = response?.data?.startseite.data.attributes
  const picks = picksResponse?.data?.picks.data
  return {
    props: {
      page,
      picks
    }
  }
}